export const ERROR_CODE = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  FILE_REQUIRED: "FILE_REQUIRED",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
} as const;